### ISSUE TITLE
[TSK-273] Basic walkthrough of Websat Planckster

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#13]
Go over all of the pages in Websat Planckster

- [ ] List source data
- [ ] Upload a file
- [ ] Download a file
- [ ] Go to different research contexts
- [ ] Go to conversations
- [ ] Start a new conversation and send a simple message, retrieve a response

**Comment by Deeptikandhol10** [comment]
@alebg, what's the status of this activity?

**Comment by Deeptikandhol10** [comment]
@alebg, what's the status of this activity? Done?

**Comment by maany** [comment]
Aborted
