### ISSUE TITLE
[TSK-280] A guide on how to run scrapers locally

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#17]
Create a guide detailing how you can set up Sentinel Scraper locally

**Comment by Deeptikandhol10** [comment]
@Rahul-7131, what is the status of this activity?

**Comment by Rahul-7131** [comment]
Working on it, if everything goes as intended most probably I'll complete it by tonight or tomorrow

**Comment by Deeptikandhol10** [comment]
Perfect.

**Comment by Rahul-7131** [comment]
Done with the documentation for setup of sentinel scraper, let me know if any further additions are needed to this.

**Comment by Deeptikandhol10** [comment]
@maany could you review it ?

**Comment by Deeptikandhol10** [comment]
@maany  could you review it?

**Comment by ydamit** [comment]
It looks like this same set of edits in [this PR](https://github.com/dream-aim-deliver/planckster-docs/pull/22) is being merged in the [Guide for running Kubeflow pipelines PR](https://github.com/dream-aim-deliver/planckster-docs/pull/25). Maybe we can just close this PR in favor of that one (where I've added a couple suggestions)?

**Comment by Rahul-7131** [comment]
yeah It seems I have merged two Issues into one PR, I'll close this PR and link that one instead

**Comment by Deeptikandhol10** [comment]
@Rahul-7131 . what's the status of this activity ? Done?

**Comment by Rahul-7131** [comment]
Yes @Deeptikandhol10 this is done
