### ISSUE TITLE
[TSK-195] document core concepts of planckster ecosystem

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#3]
https://www.notion.so/Document-core-concepts-of-Planckster-Ecosystem-8161999da6f846b1898f8c77af2c8e62?pvs=4
Write a documentation page to discuss core concepts of the Planckster Ecosystem like
Research Contexts, Source Data, User, Conversations,

**Comment by maany** [comment]
@alebg is on it with Alejandra

**Comment by Deeptikandhol10** [comment]
@alebg , what's the status of this activity? Done?
