### ISSUE TITLE
[TSK-266] Describe details of each data scraper

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#4]
Provide a description of what data scrapers do ( register data to kernel, upload data to MinIO, produce logs, generate path names)
Create a page in the concepts section, one for each data scraper i.e.
- Telegram scraper
- Twiiter Scraper
- Sentinel Scraper

Describe how they work:

- What inputs they need
- What files they produce
- What external API tokens they need and how should one retrieve them
- What relevant logs they provide
- How can you run them locally ( redirect to the section in the guides where we describe how to run data scrapers locally)

**Comment by Deeptikandhol10** [comment]
@harsh010102 , what's the status of this activity?

**Comment by harsh010102** [comment]
@Deeptikandhol10 sending a PR today! sentinel docs are done.

**Comment by Deeptikandhol10** [comment]
Okay, perfect.

**Comment by Deeptikandhol10** [comment]
@ydamit , could you please review it?

**Comment by ydamit** [comment]
On it!

**Comment by harsh010102** [comment]
@Deeptikandhol10 i guess laurent and mayank are going to review the docs.

**Comment by Deeptikandhol10** [comment]
Thanks, it will be taken care of.

**Comment by Deeptikandhol10** [comment]
@ydamit , is the review done?
