### ISSUE TITLE
[TSK-267] Description of pipelines for disaster tracking usecase

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#5]
Describe how the pipeline elements work together for the disaster and climate use cases.

Provide details on the DAG we have created in Kubeflow
Describe how augmentation works based on the outputs of the scraping pipeline in the disaster usecase
Think of any other relevant details with Laurent that should be added to the documentation

**Comment by Deeptikandhol10** [comment]
@sk-ram , what's the status of this activity?
