### ISSUE TITLE
[TSK-166] Create a Guide explaining how to run data pipelines using Kubeflow

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#7]
Create a guide on how to run a kubeflow pipeline. Use the scrapers and augmentation pipeline as examples.
Try to walk through the details of the run as it is happening.

**Comment by Deeptikandhol10** [comment]
@Rahul-7131 , what's the status of this activity?

**Comment by Deeptikandhol10** [comment]
Okay perfect

**Comment by Rahul-7131** [comment]
Let me know the feedback on this guide, if any more details need to be added or any other changes have to be made, I feel I can make it more polished if needed.

**Comment by ydamit** [comment]
Review provided!

**Comment by Deeptikandhol10** [comment]
@maany, review is done, update it?

**Comment by Rahul-7131** [comment]
Yes @Deeptikandhol10 this is completed
