### ISSUE TITLE
[TSK-268] Utilizing scraped data from pipeline to create a jupyter notebook in kubeflow and doing some basic analysis

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#8]
re-use the scraping-demos notebook on kubeflow and write a step by step guide on how someone would create it from scratch ( set up packages, set up the structure to fetch data from KP, MinIO etc)

**Comment by Deeptikandhol10** [comment]
@Rahul-7131 , what's the status of this activity?

**Comment by Rahul-7131** [comment]
@sk-ram has already linked a pr to resolve this issue, I'm working on the other remaining tickets

**Comment by Deeptikandhol10** [comment]
Okay, @manny could you have a look?

**Comment by ydamit** [comment]
Review provided!

**Comment by Deeptikandhol10** [comment]
Thanks @ydamit 
@maany , review done, update it ?

**Comment by Deeptikandhol10** [comment]
@Rahul-7131 , Is it done now?

**Comment by Rahul-7131** [comment]
This PR was linked by @sk-ram , I think he would be able to answer it better?
