### ISSUE TITLE
[TSK-269] Creating a new pipeline in kubeflow using existing scrapers and custom augmentation

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#9]
Create a guide on how to create a new kubeflow notebook with access to kubeflow pipelines. Then show how to create your own DAG with existing pipeline elements ( scrapers and augmentation repos).

Then generate the pipeline and run it in Kubeflow.

**Comment by Deeptikandhol10** [comment]
@sk-ram, what's the status of this activity?

**Comment by Deeptikandhol10** [comment]
@sk-ram , any progress?
